### ISSUE TITLE
Invalid UNC path??

### ISSUE THREAD

**Issue by Ringosystems** [aaronparker/vcredist#47] opened 2019-05-08 23:57 UTC
# Current Behavior

What is the current behavior?

When executing the following commands I get an error message

$VcList = Get-VcList

Get-VcRedist -VcList $VcList -Path "C:\Temp\VcRedist"

Import-VcConfigMgrApplication -VcList $VcList -Path "C:\Temp\VcRedist" -CMPath "\\sccm\source$\Misc\Dependencies" -SMSSiteCode SIM -Silent

# Failure Information (for bugs)

Get-Item : Cannot find path '\\sccm\source$\Misc\Dependencies\' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.132\Public\Import-VcConfigMgrApplication.ps1:183 char:68
+ ...     ContentLocation             = "$($(Get-Item -Path $CMPath).FullNa ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\sccm\source$\Misc\Dependencies\:String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

WARNING: Directory path '\2008\x64\SP1MFC' does not appear to be a valid UNC path. Must be in the format of
\\myserver\share
Add-CMScriptDeploymentType :
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.132\Public\Import-VcConfigMgrApplication.ps1:194 char:36
+ ...             $app | Add-CMScriptDeploymentType @cmScriptParams | Out-N ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Confi...mentTypeCommand:AddScriptDeploymentTypeCommand) [Add
   -CMScriptDeploymentType], InvalidOperationException
    + FullyQualifiedErrorId : ContentValidationError,Microsoft.ConfigurationManagement.Cmdlets.AppMan.Commands.AddScri
   ptDeploymentTypeCommand

Failed to add script deployment type with error System.InvalidOperationException
System.Management.Automation.CmdletInvocationException: Validation of input parameters failed. Cannot continue. --->
System.InvalidOperationException: Validation of input parameters failed. Cannot continue.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame).
At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.132\Public\Import-VcConfigMgrApplication.ps1:197 char:29
+ ...             Throw "Failed to add script deployment type with error $C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to add s...edFrame frame).:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to add script deployment type with error System.InvalidOperationException System.
   Management.Automation.CmdletInvocationException: Validation of input parameters failed. Cannot continue. ---> Syst
  em.InvalidOperationException: Validation of input parameters failed. Cannot continue.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Excepti
   on exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Step 1 $VcList = Get-VcList
Step 2 Get-VcRedist -VcList $VcList -Path "C:\Temp\VcRedist"
Step 3 Import-VcConfigMgrApplication -VcList $VcList -Path "C:\Temp\VcRedist" -CMPath "\\sccm\source$\Misc\Dependencies" -SMSSiteCode SIM -Silent

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: 2.0.132
* **PowerShell Version**: 5.1
* **Operating System**: Server 2016 1607 LTSB

## Failure Logs

Please include any relevant log snippets or files here.

I tried several different locations as well as one with the share path not being hidden.  I get the list and download to the local file system without issue.  The final command copies all of the local content to the share then errors while creating the first application.  The paths and variables are accurate.

**Comment by mcornille** [comment] 2019-05-10 15:05
Hi,

The problem is that there is a get-item on line 183 but don't think that its needed.
I was able to fix it by changing line 183 from
`ContentLocation             = "$($(Get-Item -Path $CMPath).FullName)\$($Vc.Release)\$($Vc.Architecture)\$($Vc.ShortName)"`
to the following:
`ContentLocation             = "$($CMPath)\$($Vc.Release)\$($Vc.Architecture)\$($Vc.ShortName)"`

After that all is ok

**Comment by Ringosystems** [comment] 2019-05-10 16:30
Mixed success.  I made the change to line 183 and got the results that I expected however once it appeared that the script was complete i got the following error:
Failed to add script deployment type with error.


At C:\Program Files\WindowsPowerShell\Modules\VcRedist\2.0.132\Public\Import-VcConfigMgrApplication.ps1:198 char:29
+ ...             Throw "Failed to add script deployment type with error $C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to add s...pe with error .:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to add script deployment type with error .

The content looks good but I still got this error.

Thanks,

Mark Ringo

**Comment by aaronparker** [comment] 2019-05-11 12:29
I've added the fix for line 183 in `Import-VcConfigMgrApplication` in commit aede38b50a379d6e608ff62859fcecef6291ac42. 2.0.138 pushed to the gallery.

I don't have a ConfigMgr environment in my lab right now, so if you could re-test that would be great.

**Comment by beanmeister** [comment] 2020-01-06 05:26
Tested this with current version; getting the same error still. Confirmed resolved by anyone else?
PS C:\Windows\system32> Import-VcConfigMgrApplication -vclist $List -Path $DownloadPath -CMPath "\\PkgBox\repository$
\Microsoft\Microsoft_Visual_Studio_Redistributables\" -Silent
Import-VcConfigMgrApplication : Cannot validate argument on parameter 'CMPath'.
\\PkgBox\repository$\Microsoft\Microsoft_Visual_Studio_Redistributables\ must be a valid UNC path.
At line:1 char:73
+ ... ath -CMPath "\\wprpkg101\repository$\Microsoft\Microsoft_Visual_Studi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-VcConfigMgrApplication], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Import-VcConfigMgrApplication

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.0.163    VcRedist                            PSGallery            A module for lifecycle management of the Microso...

**Comment by mcornille** [comment] 2020-01-06 07:09
> Tested this with current version; getting the same error still. Confirmed resolved by anyone else?
> PS C:\Windows\system32> Import-VcConfigMgrApplication -vclist $List -Path $DownloadPath -CMPath "\PkgBox\repository$
> \Microsoft\Microsoft_Visual_Studio_Redistributables" -Silent
> Import-VcConfigMgrApplication : Cannot validate argument on parameter 'CMPath'.
> \PkgBox\repository$\Microsoft\Microsoft_Visual_Studio_Redistributables\ must be a valid UNC path.
> At line:1 char:73
> 
> * ... ath -CMPath "\wprpkg101\repository$\Microsoft\Microsoft_Visual_Studi ...
> * ```
>               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>   
>   * CategoryInfo          : InvalidData: (:) [Import-VcConfigMgrApplication], ParameterBindingValidationException
>   * FullyQualifiedErrorId : ParameterArgumentValidationError,Import-VcConfigMgrApplication
> 
> Version Name Repository Description
> 
> 2.0.163 VcRedist PSGallery A module for lifecycle management of the Microso...

Can you check your path, in your post i see only 1 backslash in the beginning. UNC starts with 2. Also its better to use single quotes around your path as it contains a $ sign used by powershell to define a variable. if you are using variables in your path you need to use double quotes but escape the $ signs from repository.
Let me know if that fixed it or not.

**Comment by beanmeister** [comment] 2020-01-06 23:35
No luck there. Using 2 backslashes, i think the single quote fixed that part, but doesn't fix the overall issue.
Am i missing something, or does the parameter validation do the opposite of what its meant to with the !([bool].
If i just take my path and do a System.URI IsUNC check, it comes out as TRUE. Then using the parameter validation line of code, I always get the error thrown regardless. Take out the ! before boolean and I get expected output.

PS C:\Windows\system32> $CMPath = '\\wprpkg101\repository$\Microsoft\Microsoft_Visual_Studio_Redistributables\'
PS C:\Windows\system32> $cmpath
\\wprpkg101\repository$\Microsoft\Microsoft_Visual_Studio_Redistributables\
PS C:\Windows\system32> ([System.Uri]$CMPath).IsUnc
True
PS C:\Windows\system32> If (!([bool]([System.Uri]$CMPath).IsUnc)) { Write-output "test" } Else { Throw "$_ must be a valid UNC path." }
 must be a valid UNC path.
At line:1 char:74
+ ... { Write-output "test" } Else { Throw "$_ must be a valid UNC path." }
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ( must be a valid UNC path.:String) [], RuntimeException
    + FullyQualifiedErrorId :  must be a valid UNC path.

PS C:\Windows\system32> If (([bool]([System.Uri]$CMPath).IsUnc)) { Write-output "test" } Else { Throw "$_ must be a valid UNC path." }
test

**Comment by beanmeister** [comment] 2020-01-08 03:04
Update; Got the code to work fine by doing three things.
1. removing the "!" before the boolean validation.
2. If the download path and the CMpath are the same, it cracks it (copied the files to destination myself, unsure if script was meant to do this). Changed to separate download path by itself and it was fine.
3. If the CMPath included a \ at the end, it doesnt account for that. Havent had time to go further into the code, but is it using join-path to append subfolders?

**Comment by aaronparker** [comment] 2020-02-03 09:45
Added a fix in f62aa28cc24215ba6814934e7f83982abe0add38. Still requires some more testing.

**Closed** 2021-11-08 10:46 UTC
Labels: bug
